apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
namespace: beyla-system
configMapGenerator:
  - name: beyla-config
    behavior: merge
    literals:
      - |
        STAGING_OVERRIDES=true
