apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
namePrefix: canary-
namespace: beyla-system
patches:
  - target: { kind: DaemonSet, name: beyla }
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector/beyla.grafana.com~1canary
        value: "true"
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests: { cpu: 50m,  memory: 150Mi }
          limits:   { cpu: 250m, memory: 400Mi }
